/**
 * A mandala drawn from maths, not an image file.
 *
 * Every ring is generated by rotating one motif N times, so the
 * geometry is exact — hand-drawn petals never line up this cleanly.
 * Colour comes from CSS vars, so it re-themes with the site instead
 * of being baked into a yellow PNG.
 *
 * Rings are separate <g> elements so they can counter-rotate: a single
 * spinning object reads as a loading spinner, layers turning against
 * each other read as something alive.
 */

/** Repeat one motif `count` times around the centre. */
const ring = (count, render) =>
  Array.from({ length: count }, (_, i) => {
    const angle = (i / count) * 360;
    return <g key={i} transform={`rotate(${angle} 250 250)`}>{render(i)}</g>;
  });

export function Mandala({ className, style, spin = true }) {
  return (
    <svg
      viewBox="0 0 500 500"
      className={className}
      style={style}
      fill="none"
      aria-hidden
      focusable="false"
    >
      {/* ── outer: lotus petals, slowest, clockwise ── */}
      <g
        style={{
          transformOrigin: "250px 250px",
          animation: spin ? "mandala-spin 240s linear infinite" : undefined,
        }}
      >
        {ring(24, () => (
          <path
            d="M250 18 C266 52 266 74 250 104 C234 74 234 52 250 18 Z"
            stroke="currentColor"
            strokeWidth="0.7"
            strokeOpacity="0.55"
          />
        ))}
        <circle cx="250" cy="250" r="232" stroke="currentColor" strokeWidth="0.5" strokeOpacity="0.35" />
        <circle cx="250" cy="250" r="222" stroke="currentColor" strokeWidth="0.5" strokeOpacity="0.2" strokeDasharray="1 9" />
      </g>

      {/* ── second: pointed arches, anticlockwise ── */}
      <g
        style={{
          transformOrigin: "250px 250px",
          animation: spin ? "mandala-spin 170s linear infinite reverse" : undefined,
        }}
      >
        {ring(16, () => (
          <>
            <path
              d="M250 104 C272 132 272 158 250 186 C228 158 228 132 250 104 Z"
              stroke="currentColor"
              strokeWidth="0.8"
              strokeOpacity="0.6"
            />
            <circle cx="250" cy="146" r="3.4" stroke="currentColor" strokeWidth="0.6" strokeOpacity="0.5" />
          </>
        ))}
        <circle cx="250" cy="250" r="196" stroke="currentColor" strokeWidth="0.6" strokeOpacity="0.4" />
      </g>

      {/* ── third: diamonds + beads, clockwise, faster ── */}
      <g
        style={{
          transformOrigin: "250px 250px",
          animation: spin ? "mandala-spin 120s linear infinite" : undefined,
        }}
      >
        {ring(32, (i) => (
          <>
            <rect
              x="246"
              y="196"
              width="8"
              height="8"
              transform="rotate(45 250 200)"
              stroke="currentColor"
              strokeWidth="0.6"
              strokeOpacity={i % 2 ? 0.28 : 0.55}
            />
            {i % 4 === 0 && <circle cx="250" cy="214" r="1.6" fill="currentColor" fillOpacity="0.5" />}
          </>
        ))}
        <circle cx="250" cy="250" r="160" stroke="currentColor" strokeWidth="0.5" strokeOpacity="0.3" />
      </g>

      {/* ── fourth: interlaced teardrops, anticlockwise ── */}
      <g
        style={{
          transformOrigin: "250px 250px",
          animation: spin ? "mandala-spin 90s linear infinite reverse" : undefined,
        }}
      >
        {ring(12, () => (
          <path
            d="M250 160 C268 186 268 206 250 226 C232 206 232 186 250 160 Z"
            stroke="currentColor"
            strokeWidth="0.9"
            strokeOpacity="0.65"
          />
        ))}
        {ring(12, () => (
          <path d="M250 132 L258 152 L250 160 L242 152 Z" stroke="currentColor" strokeWidth="0.6" strokeOpacity="0.4" />
        ))}
      </g>

      {/* ── core rosette, slow clockwise ── */}
      <g
        style={{
          transformOrigin: "250px 250px",
          animation: spin ? "mandala-spin 60s linear infinite" : undefined,
        }}
      >
        {ring(8, () => (
          <path
            d="M250 214 C262 230 262 244 250 258 C238 244 238 230 250 214 Z"
            stroke="currentColor"
            strokeWidth="0.9"
            strokeOpacity="0.7"
          />
        ))}
        <circle cx="250" cy="250" r="30" stroke="currentColor" strokeWidth="0.7" strokeOpacity="0.5" />
        <circle cx="250" cy="250" r="18" stroke="currentColor" strokeWidth="0.6" strokeOpacity="0.35" />
        <circle cx="250" cy="250" r="4" fill="currentColor" fillOpacity="0.6" />
      </g>
    </svg>
  );
}
